USE Satchpack
GO

IF EXISTS (SELECT 1
		   FROM INFORMATION_SCHEMA.TABLES
		   WHERE TABLE_NAME = 'Product')
CREATE TABLE Product (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	SKU NVARCHAR(30) NOT NULL UNIQUE,
	Name NVARCHAR(30) NOT NULL,
	Description NVARCHAR(200) NOT NULL,
	Weight DECIMAL NOT NULL,
	Price DECIMAL NOT NULL
)
GO