USE Satchpack
GO

-- Creates the Customer table if it doesn't exist.
IF NOT EXISTS (SELECT 1
		   FROM INFORMATION_SCHEMA.TABLES
		   WHERE TABLE_NAME = 'Customer')
CREATE TABLE Customer (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Address1 NVARCHAR(200) NOT NULL,
	Address2 NVARCHAR(200) NOT NULL,
	City NVARCHAR(30) NOT NULL,
	State NVARCHAR(30) NOT NULL,
	PostalCode NVARCHAR(30) NOT NULL,
	Country NVARCHAR(30) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	Phone NVARCHAR(30) NOT NULL
)
GO