USE Satchpack
GO

IF EXISTS (SELECT 1
		   FROM INFORMATION_SCHEMA.TABLES
		   WHERE TABLE_NAME = 'ShippingMethod')
CREATE TABLE ShippingMethod (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Carrier NVARCHAR(100) NOT NULL,
	Method NVARCHAR(100) NOT NULL,
	TrackingNumber NVARCHAR(100) NOT NULL
)
GO