USE Satchpack
GO

IF NOT EXISTS (SELECT 1
		   FROM INFORMATION_SCHEMA.TABLES
		   WHERE TABLE_NAME = 'Invoice')
CREATE TABLE Invoice (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CustomerId INT NOT NULL REFERENCES Customer(Id),
	ShippingMethodId INT NOT NULL REFERENCES ShippingMethod(Id),
	OrderDate DATETIME NOT NULL,
	InvoiceTotal DECIMAL NOT NULL
)
GO